#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE dex;
    CREATE DATABASE grafana;
    CREATE USER dex WITH PASSWORD '$POSTGRES_PASSWORD';
    CREATE USER grafana WITH PASSWORD '$POSTGRES_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE dex TO dex;
    GRANT ALL PRIVILEGES ON DATABASE grafana TO grafana;
EOSQL
